### ISSUE TITLE
cached images have black background

### ISSUE THREAD

**Issue by Bodo1981** [florent37/DaVinci#5]
when an image is retrieved from cached the image always has a black background. transparency is lost

first load:
![initial_load](https://cloud.githubusercontent.com/assets/1597580/7280967/cdbe7224-e926-11e4-9017-877ec48a1070.png)

from cache:
![from_cache](https://cloud.githubusercontent.com/assets/1597580/7280966/cdbad8d0-e926-11e4-919e-527141570d14.png)

**Comment by florent37** [comment]
Thanks for the report, I saved the image as JPG, and didn't think about the
transparency. I'll make a fix saving bitmaps into PNG and publish a new
version, 1.2 I think

**Comment by florent37** [comment]
I fixed it in the 1.0.2, can you try ?

**Comment by Bodo1981** [comment]
great job. thx
